set_property PACKAGE_PIN U18 [get_ports clk]
set_property PACKAGE_PIN L1 [get_ports {rt[7]}]
set_property PACKAGE_PIN P1 [get_ports {rt[6]}]
set_property PACKAGE_PIN N3 [get_ports {rt[5]}]
set_property PACKAGE_PIN P3 [get_ports {rt[4]}]
set_property PACKAGE_PIN U3 [get_ports {rt[3]}]
set_property PACKAGE_PIN W3 [get_ports {rt[2]}]
set_property PACKAGE_PIN V3 [get_ports {rt[1]}]
set_property PACKAGE_PIN V13 [get_ports {rt[0]}]
set_property PACKAGE_PIN V14 [get_ports {rs[7]}]
set_property PACKAGE_PIN U14 [get_ports {rs[6]}]
set_property PACKAGE_PIN U15 [get_ports {rs[5]}]
set_property PACKAGE_PIN W18 [get_ports {rs[4]}]
set_property PACKAGE_PIN V19 [get_ports {rs[3]}]
set_property PACKAGE_PIN U19 [get_ports {rs[2]}]
set_property PACKAGE_PIN E19 [get_ports {rs[1]}]
set_property PACKAGE_PIN U16 [get_ports {rs[0]}]

set_property PULLTYPE PULLDOWN [get_ports clk]

set_property IOSTANDARD LVCMOS33 [get_ports {rs[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rs[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rs[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rs[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rs[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rs[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rs[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rs[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rt[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rt[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rt[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rt[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rt[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rt[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rt[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rt[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk_IBUF]

